import React from 'react';
import { getLogger } from '../../../../logic/adapter';
import { selectPromptGroups, useAppSelector } from '../../../../logic/store';

const logger = getLogger('InfoView');

const InfoView: React.FC = () => {
    const promptGroups = useAppSelector(selectPromptGroups);

    if (!promptGroups) {
        logger.logDebug('Prompt groups not loaded yet, showing loading state');
        return (
            <div style={{ padding: 'var(--space-4)', overflow: 'auto', height: '100%' }}>
                <h2>About Text Processor</h2>
                <p>Text Processor is a powerful text transformation tool that uses Large Language Models (LLMs).</p>
                <h3>Available Actions</h3>
                <p>Loading action information…</p>
            </div>
        );
    }

    if (Object.keys(promptGroups.promptGroups).length === 0) {
        return (
            <div style={{ padding: 'var(--space-4)', overflow: 'auto', height: '100%' }}>
                <h2>About Text Processor</h2>
                <p>No action groups available.</p>
            </div>
        );
    }

    return (
        <div style={{ padding: 'var(--space-4)', overflow: 'auto', height: '100%' }}>
            <h2>About Text Processor</h2>
            <p>
                Text Processor is a powerful text transformation tool that uses Large Language Models (LLMs) to perform various text operations
                including translation, summarization, formatting, and more.
            </p>
            <h3 style={{ marginTop: 'var(--space-4)' }}>How It Works</h3>
            <p>
                The application sends your text to AI models that process and transform it based on the selected action. Results are generated by AI
                and should be reviewed for accuracy.
            </p>
            <h3 style={{ marginTop: 'var(--space-4)' }}>Available Actions</h3>
            {Object.entries(promptGroups.promptGroups).map(([groupId, group]) => (
                <div key={groupId} style={{ marginBottom: 'var(--space-4)' }}>
                    <h4>{group.groupName}</h4>
                    <table style={{ width: '100%', borderCollapse: 'collapse', border: '1px solid var(--line)' }}>
                        <thead>
                            <tr style={{ background: 'var(--surface-2)' }}>
                                <th style={{ padding: 'var(--space-2)', textAlign: 'left', borderBottom: '1px solid var(--line)' }}>Action Name</th>
                                <th style={{ padding: 'var(--space-2)', textAlign: 'left', borderBottom: '1px solid var(--line)' }}>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                            {Object.entries(group.prompts).map(([promptId, prompt]) => (
                                <tr key={promptId} style={{ borderBottom: '1px solid var(--line)' }}>
                                    <td style={{ padding: 'var(--space-2)', color: 'var(--ink)' }}>{prompt.name}</td>
                                    <td style={{ padding: 'var(--space-2)', color: 'var(--ink-2)' }}>{prompt.description}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            ))}
        </div>
    );
};

InfoView.displayName = 'InfoView';
export default InfoView;
