import { Box, CircularProgress, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material';
import React from 'react';
import { getLogger } from '../../../../logic/adapter';
import { selectPromptGroups, useAppSelector } from '../../../../logic/store';

const logger = getLogger('InfoView');

/**
 * Information View Component
 *
 * Displays comprehensive information about the application, including
 * - Application description and purpose
 * - Explanation of LLM processing
 * - Available actions organized by prompt groups
 *
 * Handles loading states gracefully when prompt groups are not yet loaded.
 */
const InfoView: React.FC = () => {
    const promptGroups = useAppSelector(selectPromptGroups);

    if (!promptGroups) {
        logger.logDebug('Prompt groups not loaded yet, showing loading state');
        return (
            <Box sx={{ p: 3, width: '100%', height: '100%', display: 'flex', flexDirection: 'column', overflow: 'auto' }}>
                <Typography variant="h4" gutterBottom>
                    About Text Processor
                </Typography>
                <Typography component="p">
                    Text Processor is a powerful text transformation tool that uses Large Language Models (LLMs) to perform various text operations
                    including translation, summarization, formatting, and more.
                </Typography>

                <Typography variant="h5" gutterBottom sx={{ mt: 3 }}>
                    Available Actions
                </Typography>
                <Typography component="p">Loading action information...</Typography>
                <CircularProgress />
            </Box>
        );
    }

    if (Object.keys(promptGroups.promptGroups).length === 0) {
        return (
            <Box sx={{ p: 3, overflow: 'auto', height: '100%' }}>
                <Typography variant="h4" gutterBottom>
                    About Text Processor
                </Typography>
                <Typography component="p">
                    Text Processor is a powerful text transformation tool that uses Large Language Models (LLMs) to perform various text operations
                    including translation, summarization, formatting, and more.
                </Typography>

                <Typography variant="h5" gutterBottom sx={{ mt: 3 }}>
                    Available Actions
                </Typography>
                <Typography>No action groups available.</Typography>
            </Box>
        );
    }

    return (
        <Box sx={{ p: 3, overflow: 'auto', height: '100%' }}>
            <Typography variant="h4" gutterBottom>
                About Text Processor
            </Typography>
            <Typography component="p">
                Text Processor is a powerful text transformation tool that uses Large Language Models (LLMs) to perform various text operations
                including translation, summarization, formatting, and more.
            </Typography>

            <Typography variant="h5" gutterBottom sx={{ mt: 3 }}>
                How It Works
            </Typography>
            <Typography component="p">
                The application sends your text to advanced AI models that process and transform it based on the selected action. Results are
                generated by AI and should be reviewed for accuracy.
            </Typography>

            <Typography variant="h5" gutterBottom sx={{ mt: 3 }}>
                Available Actions
            </Typography>
            {Object.entries(promptGroups.promptGroups).map(([groupId, group]) => (
                <Box key={groupId} sx={{ mb: 4 }}>
                    <Typography variant="h6" gutterBottom>
                        {group.groupName}
                    </Typography>
                    <TableContainer component={Paper} elevation={0} sx={{ border: `1px solid 'secondary.dark'` }}>
                        <Table size="small">
                            <TableHead sx={{ backgroundColor: 'secondary.dark' }}>
                                <TableRow>
                                    <TableCell sx={{ color: 'secondary.contrastText', fontWeight: 'bold' }}>Action Name</TableCell>
                                    <TableCell sx={{ color: 'secondary.contrastText', fontWeight: 'bold' }}>Description</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody sx={{ backgroundColor: 'secondary.light' }}>
                                {Object.entries(group.prompts).map(([promptId, prompt]) => (
                                    <TableRow
                                        key={promptId}
                                        sx={{ 'color': 'secondary.contrastText', '&:hover': { backgroundColor: 'rgba(255, 64, 129, 0.08)' } }}
                                    >
                                        <TableCell sx={{ color: 'secondary.contrastText' }}>{prompt.name}</TableCell>
                                        <TableCell sx={{ color: 'secondary.contrastText' }}>{prompt.description}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </TableContainer>
                </Box>
            ))}
        </Box>
    );
};

InfoView.displayName = 'InfoView';
export default InfoView;
