// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_state.sql

package store

import (
	"context"
	"database/sql"
)

const getCurrentProviderID = `-- name: GetCurrentProviderID :one
SELECT current_provider_id FROM app_state WHERE id = 1
`

func (q *Queries) GetCurrentProviderID(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCurrentProviderID)
	var current_provider_id sql.NullString
	err := row.Scan(&current_provider_id)
	return current_provider_id, err
}

const setCurrentProviderID = `-- name: SetCurrentProviderID :exec
INSERT INTO app_state (id, current_provider_id) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET current_provider_id = excluded.current_provider_id
`

func (q *Queries) SetCurrentProviderID(ctx context.Context, currentProviderID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, setCurrentProviderID, currentProviderID)
	return err
}
