// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package store

import (
	"context"
)

const addHistory = `-- name: AddHistory :exec
INSERT INTO history (
  id, created_at, kind, title, input_text, output_text, applied,
  provider_name, model, input_lang, output_lang, format,
  duration_ms, inferences, status, error_code, failed_index
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddHistoryParams struct {
	ID           string
	CreatedAt    int64
	Kind         string
	Title        string
	InputText    string
	OutputText   string
	Applied      string
	ProviderName string
	Model        string
	InputLang    string
	OutputLang   string
	Format       string
	DurationMs   int64
	Inferences   int64
	Status       string
	ErrorCode    string
	FailedIndex  int64
}

func (q *Queries) AddHistory(ctx context.Context, arg AddHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addHistory,
		arg.ID,
		arg.CreatedAt,
		arg.Kind,
		arg.Title,
		arg.InputText,
		arg.OutputText,
		arg.Applied,
		arg.ProviderName,
		arg.Model,
		arg.InputLang,
		arg.OutputLang,
		arg.Format,
		arg.DurationMs,
		arg.Inferences,
		arg.Status,
		arg.ErrorCode,
		arg.FailedIndex,
	)
	return err
}

const clearHistory = `-- name: ClearHistory :exec
DELETE FROM history
`

func (q *Queries) ClearHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearHistory)
	return err
}

const countHistory = `-- name: CountHistory :one
SELECT count(*) FROM history
`

func (q *Queries) CountHistory(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHistory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHistory = `-- name: DeleteHistory :exec
DELETE FROM history WHERE id = ?
`

func (q *Queries) DeleteHistory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHistory, id)
	return err
}

const getHistory = `-- name: GetHistory :one
SELECT id, created_at, kind, title, input_text, output_text, applied, provider_name, model, input_lang, output_lang, format, duration_ms, inferences, status, error_code, failed_index FROM history WHERE id = ?
`

func (q *Queries) GetHistory(ctx context.Context, id string) (History, error) {
	row := q.db.QueryRowContext(ctx, getHistory, id)
	var i History
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Kind,
		&i.Title,
		&i.InputText,
		&i.OutputText,
		&i.Applied,
		&i.ProviderName,
		&i.Model,
		&i.InputLang,
		&i.OutputLang,
		&i.Format,
		&i.DurationMs,
		&i.Inferences,
		&i.Status,
		&i.ErrorCode,
		&i.FailedIndex,
	)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT id, created_at, kind, title, input_text, output_text, applied, provider_name, model, input_lang, output_lang, format, duration_ms, inferences, status, error_code, failed_index FROM history ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListHistoryParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.Title,
			&i.InputText,
			&i.OutputText,
			&i.Applied,
			&i.ProviderName,
			&i.Model,
			&i.InputLang,
			&i.OutputLang,
			&i.Format,
			&i.DurationMs,
			&i.Inferences,
			&i.Status,
			&i.ErrorCode,
			&i.FailedIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHistory = `-- name: PruneHistory :exec
DELETE FROM history WHERE id NOT IN (
  SELECT id FROM history ORDER BY created_at DESC LIMIT ?
)
`

func (q *Queries) PruneHistory(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, pruneHistory, limit)
	return err
}
