// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: languages.sql

package store

import (
	"context"
)

const addLanguage = `-- name: AddLanguage :exec
INSERT INTO languages (name, sort_order) VALUES (?, ?) ON CONFLICT(name) DO NOTHING
`

type AddLanguageParams struct {
	Name      string
	SortOrder int64
}

func (q *Queries) AddLanguage(ctx context.Context, arg AddLanguageParams) error {
	_, err := q.db.ExecContext(ctx, addLanguage, arg.Name, arg.SortOrder)
	return err
}

const listLanguages = `-- name: ListLanguages :many
SELECT name FROM languages ORDER BY sort_order, name
`

func (q *Queries) ListLanguages(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLanguage = `-- name: RemoveLanguage :exec
DELETE FROM languages WHERE name = ?
`

func (q *Queries) RemoveLanguage(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, removeLanguage, name)
	return err
}
