// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type AppState struct {
	ID                int64
	CurrentProviderID sql.NullString
}

type History struct {
	ID           string
	CreatedAt    int64
	Kind         string
	Title        string
	InputText    string
	OutputText   string
	Applied      string
	ProviderName string
	Model        string
	InputLang    string
	OutputLang   string
	Format       string
	DurationMs   int64
	Inferences   int64
	Status       string
	ErrorCode    string
	FailedIndex  int64
}

type Language struct {
	Name      string
	SortOrder int64
}

type Provider struct {
	ID              string
	Name            string
	Kind            string
	BaseUrl         string
	AuthScheme      string
	ApiKeyEnvVar    string
	ApiVersion      string
	SelectedModel   string
	CompletionPath  string
	ModelsPath      string
	UseCustomModels int64
	Headers         string
	CustomModels    string
	CreatedAt       int64
	UpdatedAt       int64
}

type Setting struct {
	Key   string
	Value string
	Type  string
}

type Stack struct {
	ID             string
	Name           string
	Icon           string
	DefaultFormat  string
	DefaultInLang  string
	DefaultOutLang string
	CreatedAt      int64
	UpdatedAt      int64
}

type StackStep struct {
	StackID  string
	Position int64
	ActionID string
}
