// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package store

import (
	"context"
)

const countProviders = `-- name: CountProviders :one
SELECT count(*) FROM providers
`

func (q *Queries) CountProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :exec
INSERT INTO providers (
  id, name, kind, base_url, auth_scheme, api_key_env_var, api_version,
  selected_model, completion_path, models_path, use_custom_models,
  headers, custom_models, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProviderParams struct {
	ID              string
	Name            string
	Kind            string
	BaseUrl         string
	AuthScheme      string
	ApiKeyEnvVar    string
	ApiVersion      string
	SelectedModel   string
	CompletionPath  string
	ModelsPath      string
	UseCustomModels int64
	Headers         string
	CustomModels    string
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) error {
	_, err := q.db.ExecContext(ctx, createProvider,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.AuthScheme,
		arg.ApiKeyEnvVar,
		arg.ApiVersion,
		arg.SelectedModel,
		arg.CompletionPath,
		arg.ModelsPath,
		arg.UseCustomModels,
		arg.Headers,
		arg.CustomModels,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = ?
`

func (q *Queries) DeleteProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, kind, base_url, auth_scheme, api_key_env_var, api_version, selected_model, completion_path, models_path, use_custom_models, headers, custom_models, created_at, updated_at FROM providers WHERE id = ?
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.AuthScheme,
		&i.ApiKeyEnvVar,
		&i.ApiVersion,
		&i.SelectedModel,
		&i.CompletionPath,
		&i.ModelsPath,
		&i.UseCustomModels,
		&i.Headers,
		&i.CustomModels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, kind, base_url, auth_scheme, api_key_env_var, api_version, selected_model, completion_path, models_path, use_custom_models, headers, custom_models, created_at, updated_at FROM providers ORDER BY name
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BaseUrl,
			&i.AuthScheme,
			&i.ApiKeyEnvVar,
			&i.ApiVersion,
			&i.SelectedModel,
			&i.CompletionPath,
			&i.ModelsPath,
			&i.UseCustomModels,
			&i.Headers,
			&i.CustomModels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE providers SET
  name = ?, kind = ?, base_url = ?, auth_scheme = ?, api_key_env_var = ?,
  api_version = ?, selected_model = ?, completion_path = ?, models_path = ?,
  use_custom_models = ?, headers = ?, custom_models = ?, updated_at = ?
WHERE id = ?
`

type UpdateProviderParams struct {
	Name            string
	Kind            string
	BaseUrl         string
	AuthScheme      string
	ApiKeyEnvVar    string
	ApiVersion      string
	SelectedModel   string
	CompletionPath  string
	ModelsPath      string
	UseCustomModels int64
	Headers         string
	CustomModels    string
	UpdatedAt       int64
	ID              string
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateProvider,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.AuthScheme,
		arg.ApiKeyEnvVar,
		arg.ApiVersion,
		arg.SelectedModel,
		arg.CompletionPath,
		arg.ModelsPath,
		arg.UseCustomModels,
		arg.Headers,
		arg.CustomModels,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
