// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddHistory(ctx context.Context, arg AddHistoryParams) error
	AddLanguage(ctx context.Context, arg AddLanguageParams) error
	ClearHistory(ctx context.Context) error
	CountHistory(ctx context.Context) (int64, error)
	CountProviders(ctx context.Context) (int64, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) error
	DeleteAllStackSteps(ctx context.Context, stackID string) error
	DeleteHistory(ctx context.Context, id string) error
	DeleteProvider(ctx context.Context, id string) error
	DeleteStack(ctx context.Context, id string) error
	GetCurrentProviderID(ctx context.Context) (sql.NullString, error)
	GetHistory(ctx context.Context, id string) (History, error)
	GetProvider(ctx context.Context, id string) (Provider, error)
	GetSetting(ctx context.Context, key string) (GetSettingRow, error)
	GetStack(ctx context.Context, id string) (Stack, error)
	GetStackSteps(ctx context.Context, stackID string) ([]string, error)
	InsertStack(ctx context.Context, arg InsertStackParams) error
	InsertStackStep(ctx context.Context, arg InsertStackStepParams) error
	ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error)
	ListLanguages(ctx context.Context) ([]string, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListStacks(ctx context.Context) ([]Stack, error)
	PruneHistory(ctx context.Context, limit int64) error
	RemoveLanguage(ctx context.Context, name string) error
	SetCurrentProviderID(ctx context.Context, currentProviderID sql.NullString) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) error
	UpdateStack(ctx context.Context, arg UpdateStackParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
