// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value, type FROM settings WHERE key = ?
`

type GetSettingRow struct {
	Value string
	Type  string
}

func (q *Queries) GetSetting(ctx context.Context, key string) (GetSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(&i.Value, &i.Type)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, type FROM settings
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Key, &i.Value, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value, type) VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, type = excluded.type
`

type UpsertSettingParams struct {
	Key   string
	Value string
	Type  string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value, arg.Type)
	return err
}
