// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stacks.sql

package store

import (
	"context"
)

const deleteAllStackSteps = `-- name: DeleteAllStackSteps :exec
DELETE FROM stack_steps WHERE stack_id = ?
`

func (q *Queries) DeleteAllStackSteps(ctx context.Context, stackID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllStackSteps, stackID)
	return err
}

const deleteStack = `-- name: DeleteStack :exec
DELETE FROM stacks WHERE id = ?
`

func (q *Queries) DeleteStack(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStack, id)
	return err
}

const getStack = `-- name: GetStack :one
SELECT id, name, icon, default_format, default_in_lang, default_out_lang, created_at, updated_at FROM stacks WHERE id = ?
`

func (q *Queries) GetStack(ctx context.Context, id string) (Stack, error) {
	row := q.db.QueryRowContext(ctx, getStack, id)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.DefaultFormat,
		&i.DefaultInLang,
		&i.DefaultOutLang,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStackSteps = `-- name: GetStackSteps :many
SELECT action_id FROM stack_steps WHERE stack_id = ? ORDER BY position
`

func (q *Queries) GetStackSteps(ctx context.Context, stackID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getStackSteps, stackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var action_id string
		if err := rows.Scan(&action_id); err != nil {
			return nil, err
		}
		items = append(items, action_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStack = `-- name: InsertStack :exec
INSERT INTO stacks (id, name, icon, default_format, default_in_lang, default_out_lang, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStackParams struct {
	ID             string
	Name           string
	Icon           string
	DefaultFormat  string
	DefaultInLang  string
	DefaultOutLang string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) InsertStack(ctx context.Context, arg InsertStackParams) error {
	_, err := q.db.ExecContext(ctx, insertStack,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.DefaultFormat,
		arg.DefaultInLang,
		arg.DefaultOutLang,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertStackStep = `-- name: InsertStackStep :exec
INSERT INTO stack_steps (stack_id, position, action_id) VALUES (?, ?, ?)
`

type InsertStackStepParams struct {
	StackID  string
	Position int64
	ActionID string
}

func (q *Queries) InsertStackStep(ctx context.Context, arg InsertStackStepParams) error {
	_, err := q.db.ExecContext(ctx, insertStackStep, arg.StackID, arg.Position, arg.ActionID)
	return err
}

const listStacks = `-- name: ListStacks :many
SELECT id, name, icon, default_format, default_in_lang, default_out_lang, created_at, updated_at FROM stacks ORDER BY name
`

func (q *Queries) ListStacks(ctx context.Context) ([]Stack, error) {
	rows, err := q.db.QueryContext(ctx, listStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stack
	for rows.Next() {
		var i Stack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.DefaultFormat,
			&i.DefaultInLang,
			&i.DefaultOutLang,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStack = `-- name: UpdateStack :exec
UPDATE stacks SET
  name = ?, icon = ?, default_format = ?, default_in_lang = ?, default_out_lang = ?, updated_at = ?
WHERE id = ?
`

type UpdateStackParams struct {
	Name           string
	Icon           string
	DefaultFormat  string
	DefaultInLang  string
	DefaultOutLang string
	UpdatedAt      int64
	ID             string
}

func (q *Queries) UpdateStack(ctx context.Context, arg UpdateStackParams) error {
	_, err := q.db.ExecContext(ctx, updateStack,
		arg.Name,
		arg.Icon,
		arg.DefaultFormat,
		arg.DefaultInLang,
		arg.DefaultOutLang,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
