// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['history']['HistoryHandler']['ClearHistory']();
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['history']['HistoryHandler']['DeleteHistoryEntry'](arg1);
}

export function GetHistoryEntry(arg1) {
  return window['go']['history']['HistoryHandler']['GetHistoryEntry'](arg1);
}

export function ListHistory(arg1, arg2) {
  return window['go']['history']['HistoryHandler']['ListHistory'](arg1, arg2);
}
