// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';

export function ClearHistory():Promise<apperr.VoidResult>;

export function DeleteHistoryEntry(arg1:string):Promise<apperr.VoidResult>;

export function GetHistoryEntry(arg1:string):Promise<apperr.HistoryEntryResult>;

export function ListHistory(arg1:number,arg2:number):Promise<apperr.HistoryListResult>;
