// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';
import {context} from '../models';

export function BrowserOpenURL(arg1:string):Promise<apperr.VoidResult>;

export function CancelAllRuns():Promise<void>;

export function ClipboardGetText():Promise<apperr.StringResult>;

export function ClipboardSetText(arg1:string):Promise<apperr.VoidResult>;

export function EnableLoggingForDev(arg1:context.Context):Promise<void>;

export function Init(arg1:context.Context):Promise<void>;

export function LogError(arg1:string):Promise<apperr.VoidResult>;

export function OpenPath(arg1:string):Promise<apperr.VoidResult>;

export function SetContext(arg1:context.Context):Promise<void>;
