// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['application']['ApplicationContextHolder']['BrowserOpenURL'](arg1);
}

export function CancelAllRuns() {
  return window['go']['application']['ApplicationContextHolder']['CancelAllRuns']();
}

export function ClipboardGetText() {
  return window['go']['application']['ApplicationContextHolder']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['application']['ApplicationContextHolder']['ClipboardSetText'](arg1);
}

export function EnableLoggingForDev(arg1) {
  return window['go']['application']['ApplicationContextHolder']['EnableLoggingForDev'](arg1);
}

export function Init(arg1) {
  return window['go']['application']['ApplicationContextHolder']['Init'](arg1);
}

export function LogError(arg1) {
  return window['go']['application']['ApplicationContextHolder']['LogError'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['application']['ApplicationContextHolder']['OpenPath'](arg1);
}

export function SetContext(arg1) {
  return window['go']['application']['ApplicationContextHolder']['SetContext'](arg1);
}
