// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';
import {stacks} from '../models';

export function CreateStack(arg1:apperr.SavedStack):Promise<apperr.StackResult>;

export function DeleteStack(arg1:string):Promise<apperr.VoidResult>;

export function DuplicateStack(arg1:string,arg2:string):Promise<apperr.StackResult>;

export function GetStack(arg1:string):Promise<apperr.StackResult>;

export function ListStacks():Promise<apperr.StacksResult>;

export function SetRepository(arg1:stacks.StackRepositoryAPI):Promise<void>;

export function SuggestedStacks():Promise<apperr.SuggestedStacksResult>;

export function UpdateStack(arg1:apperr.SavedStack):Promise<apperr.StackResult>;
