// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateStack(arg1) {
  return window['go']['stacks']['StackHandler']['CreateStack'](arg1);
}

export function DeleteStack(arg1) {
  return window['go']['stacks']['StackHandler']['DeleteStack'](arg1);
}

export function DuplicateStack(arg1, arg2) {
  return window['go']['stacks']['StackHandler']['DuplicateStack'](arg1, arg2);
}

export function GetStack(arg1) {
  return window['go']['stacks']['StackHandler']['GetStack'](arg1);
}

export function ListStacks() {
  return window['go']['stacks']['StackHandler']['ListStacks']();
}

export function SetRepository(arg1) {
  return window['go']['stacks']['StackHandler']['SetRepository'](arg1);
}

export function SuggestedStacks() {
  return window['go']['stacks']['StackHandler']['SuggestedStacks']();
}

export function UpdateStack(arg1) {
  return window['go']['stacks']['StackHandler']['UpdateStack'](arg1);
}
