// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllRuns() {
  return window['go']['actions']['ActionHandler']['CancelAllRuns']();
}

export function CancelChain(arg1) {
  return window['go']['actions']['ActionHandler']['CancelChain'](arg1);
}

export function GetActionCatalog() {
  return window['go']['actions']['ActionHandler']['GetActionCatalog']();
}

export function GetModels(arg1) {
  return window['go']['actions']['ActionHandler']['GetModels'](arg1);
}

export function PreviewPrompt(arg1) {
  return window['go']['actions']['ActionHandler']['PreviewPrompt'](arg1);
}

export function ProcessPromptChain(arg1) {
  return window['go']['actions']['ActionHandler']['ProcessPromptChain'](arg1);
}

export function SetContext(arg1) {
  return window['go']['actions']['ActionHandler']['SetContext'](arg1);
}

export function SetStackLookup(arg1) {
  return window['go']['actions']['ActionHandler']['SetStackLookup'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['actions']['ActionHandler']['TestConnection'](arg1);
}

export function TestInference(arg1) {
  return window['go']['actions']['ActionHandler']['TestInference'](arg1);
}

export function TestModels(arg1) {
  return window['go']['actions']['ActionHandler']['TestModels'](arg1);
}
