// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';
import {context} from '../models';
import {actions} from '../models';
import {settings} from '../models';

export function CancelAllRuns():Promise<void>;

export function CancelChain(arg1:string):Promise<apperr.VoidResult>;

export function GetActionCatalog():Promise<apperr.CatalogResult>;

export function GetModels(arg1:string):Promise<apperr.ModelsResult>;

export function PreviewPrompt(arg1:apperr.PromptPreviewRequest):Promise<apperr.PromptPreviewResult>;

export function ProcessPromptChain(arg1:apperr.ChainRequest):Promise<apperr.ChainResultEnv>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetStackLookup(arg1:actions.StackLookupAPI):Promise<void>;

export function TestConnection(arg1:settings.ProviderConfig):Promise<apperr.VerifyResult>;

export function TestInference(arg1:settings.ProviderConfig):Promise<apperr.VerifyResult>;

export function TestModels(arg1:settings.ProviderConfig):Promise<apperr.VerifyResult>;
