// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLanguage(arg1) {
  return window['go']['settings']['SettingsHandler']['AddLanguage'](arg1);
}

export function Configure(arg1, arg2, arg3) {
  return window['go']['settings']['SettingsHandler']['Configure'](arg1, arg2, arg3);
}

export function CreateProviderConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['CreateProviderConfig'](arg1);
}

export function DeleteProviderConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['DeleteProviderConfig'](arg1);
}

export function GetAllProviderConfigs() {
  return window['go']['settings']['SettingsHandler']['GetAllProviderConfigs']();
}

export function GetAppBehaviorConfig() {
  return window['go']['settings']['SettingsHandler']['GetAppBehaviorConfig']();
}

export function GetAppSettingsMetadata() {
  return window['go']['settings']['SettingsHandler']['GetAppSettingsMetadata']();
}

export function GetCurrentProviderConfig() {
  return window['go']['settings']['SettingsHandler']['GetCurrentProviderConfig']();
}

export function GetInferenceBaseConfig() {
  return window['go']['settings']['SettingsHandler']['GetInferenceBaseConfig']();
}

export function GetLanguageConfig() {
  return window['go']['settings']['SettingsHandler']['GetLanguageConfig']();
}

export function GetLoggingConfig() {
  return window['go']['settings']['SettingsHandler']['GetLoggingConfig']();
}

export function GetModelConfig() {
  return window['go']['settings']['SettingsHandler']['GetModelConfig']();
}

export function GetProviderConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['GetProviderConfig'](arg1);
}

export function GetSettings() {
  return window['go']['settings']['SettingsHandler']['GetSettings']();
}

export function GetUIPreferencesConfig() {
  return window['go']['settings']['SettingsHandler']['GetUIPreferencesConfig']();
}

export function ProviderPresets() {
  return window['go']['settings']['SettingsHandler']['ProviderPresets']();
}

export function RemoveLanguage(arg1) {
  return window['go']['settings']['SettingsHandler']['RemoveLanguage'](arg1);
}

export function ResetSettingsToDefault() {
  return window['go']['settings']['SettingsHandler']['ResetSettingsToDefault']();
}

export function SetAppLogger(arg1, arg2, arg3) {
  return window['go']['settings']['SettingsHandler']['SetAppLogger'](arg1, arg2, arg3);
}

export function SetAsCurrentProviderConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['SetAsCurrentProviderConfig'](arg1);
}

export function SetDefaultInputLanguage(arg1) {
  return window['go']['settings']['SettingsHandler']['SetDefaultInputLanguage'](arg1);
}

export function SetDefaultOutputLanguage(arg1) {
  return window['go']['settings']['SettingsHandler']['SetDefaultOutputLanguage'](arg1);
}

export function UpdateAppBehaviorConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateAppBehaviorConfig'](arg1);
}

export function UpdateInferenceBaseConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateInferenceBaseConfig'](arg1);
}

export function UpdateLoggingConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateLoggingConfig'](arg1);
}

export function UpdateModelConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateModelConfig'](arg1);
}

export function UpdateProviderConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateProviderConfig'](arg1);
}

export function UpdateUIPreferencesConfig(arg1) {
  return window['go']['settings']['SettingsHandler']['UpdateUIPreferencesConfig'](arg1);
}
