// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';
import {logger} from '../models';
import {zerolog} from '../models';
import {settings} from '../models';
import {logging} from '../models';
import {file} from '../models';

export function AddLanguage(arg1:string):Promise<apperr.LanguagesResult>;

export function Configure(arg1:logger.Logger,arg2:zerolog.Logger,arg3:settings.SettingsServiceAPI):Promise<void>;

export function CreateProviderConfig(arg1:apperr.ProviderConfig):Promise<apperr.ProviderResult>;

export function DeleteProviderConfig(arg1:string):Promise<apperr.VoidResult>;

export function GetAllProviderConfigs():Promise<apperr.ProvidersResult>;

export function GetAppBehaviorConfig():Promise<apperr.AppBehaviorResult>;

export function GetAppSettingsMetadata():Promise<apperr.MetadataResult>;

export function GetCurrentProviderConfig():Promise<apperr.ProviderResult>;

export function GetInferenceBaseConfig():Promise<apperr.InferenceResult>;

export function GetLanguageConfig():Promise<apperr.LanguageResult>;

export function GetLoggingConfig():Promise<apperr.LoggingResult>;

export function GetModelConfig():Promise<apperr.ModelConfigResult>;

export function GetProviderConfig(arg1:string):Promise<apperr.ProviderResult>;

export function GetSettings():Promise<apperr.SettingsResult>;

export function GetUIPreferencesConfig():Promise<apperr.UIPreferencesResult>;

export function ProviderPresets():Promise<apperr.ProviderPresetsResult>;

export function RemoveLanguage(arg1:string):Promise<apperr.LanguagesResult>;

export function ResetSettingsToDefault():Promise<apperr.SettingsResult>;

export function SetAppLogger(arg1:logging.Logger,arg2:file.FileUtilsServiceAPI,arg3:boolean):Promise<void>;

export function SetAsCurrentProviderConfig(arg1:string):Promise<apperr.ProviderResult>;

export function SetDefaultInputLanguage(arg1:string):Promise<apperr.VoidResult>;

export function SetDefaultOutputLanguage(arg1:string):Promise<apperr.VoidResult>;

export function UpdateAppBehaviorConfig(arg1:apperr.AppBehaviorConfig):Promise<apperr.AppBehaviorResult>;

export function UpdateInferenceBaseConfig(arg1:apperr.InferenceBaseConfig):Promise<apperr.InferenceResult>;

export function UpdateLoggingConfig(arg1:apperr.LoggingConfig):Promise<apperr.LoggingResult>;

export function UpdateModelConfig(arg1:apperr.ModelConfig):Promise<apperr.ModelConfigResult>;

export function UpdateProviderConfig(arg1:apperr.ProviderConfig):Promise<apperr.ProviderResult>;

export function UpdateUIPreferencesConfig(arg1:apperr.UIPreferencesConfig):Promise<apperr.UIPreferencesResult>;
